name: Minitest

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.11.0

  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        test-path:
          - test/controllers/*.rb
          - test/models/*

    services:
      pg:
        image: postgres:12.1
        ports: ['5432:5432']
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2.1
 
      - name: Bundle install and dependencies
        run: bundle install --jobs 4 --retry 3 && sudo apt-get install libpq-dev
        run: |
          bundle exec rails db:setup
      - name: Run tests
        run: bundle exec rails test ${{ matrix['test-path']}}
